version: '3.7'

services:
  core:
    build: .
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
       - ./:/app
    command: npm run start:debug
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASENAME}
      CONNECTION_STRING: 'postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASENAME}'
